name: faved-dev
services:
  apache-php:
    build: .
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./apache-conf:/etc/apache2/sites-enabled
    ports:
      - "${BACKEND_PORT:-8000}:80"
  node:
    image: node:24
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html
      - ./public/dist/:/var/www/html/dist/
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - "BACKEND_PORT=${BACKEND_PORT:-8000}"
    command: sh -c "npm install && npm run dev -- --host"